/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jastic;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static jastic.Jastic.*;

class JasticTest {
    @Test void renderTag() {
        HTMLRenderer r = new HTMLRenderer();
        String actual = r.render(tag("test", text("foobar")));
        Assertions.assertEquals("<test>\n" +
                "\tfoobar\n" +
                "</test>", actual);
    }

    @Test void render() {
        HTMLRenderer r = new HTMLRenderer();
        String actual = r.render(html(
                body(
                        text("Hello, World!")
                )
        ));
        Assertions.assertEquals("<html>\n" +
                "\t<body>\n" +
                "\t\tHello, World!\n" +
                "\t</body>\n" +
                "</html>", actual);
    }

    @Test void renderTagWithId() {
        HTMLRenderer r = new HTMLRenderer();
        String actual = r.render(tag("test", attributes(id("bar"), className("foo")), text("foobar")));
        Assertions.assertEquals("<test id=\"bar\" class=\"foo\">\n" +
                "\tfoobar\n" +
                "</test>", actual);
    }
}
