/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jastic.html;

import jastic.html.attributes.Charset;
import jastic.html.elements.Body;
import jastic.html.elements.Text;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Map;
import java.util.Stack;

import static jastic.JasticHTML.*;

class HTMLRendererTest {

    HTMLRenderer r = new HTMLRenderer();

    @Test
    void renderOverwritten() {
        HTMLRenderer stackRenderer = new HTMLRenderer() {

            @Override
            public String renderElementBody(final Map<String, Object> context, final Body body) {
                Stack<DomElement> stack = (Stack<DomElement>) context.get("stack");
                return stack.peek().getTag() + super.renderElementBody(context, body);
            }

            @Override
            public String renderElementText(final Map<String, Object> context, final Text text) {
                Stack<DomElement> stack = (Stack<DomElement>) context.get("stack");
                return stack.peek().getTag() + super.renderElementText(context, text);
            }
        };

        String actual = stackRenderer.render(html(
                body(
                        text("Hello, World!")
                )
        ));
        Assertions.assertEquals("<html>\n" +
                "html\t<body>\n" +
                "body\t\tHello, World!\n" +
                "\t</body>\n" +
                "</html>", actual);
    }

    @Test
    void renderTag() {
        String actual = r.render(tag("test", text("foobar")));
        Assertions.assertEquals("<test>\n" +
                "\tfoobar\n" +
                "</test>", actual);
    }

    @Test
    void renderManyElements() {
        String actual = r.render(text("foobar"), text("baz"));
        Assertions.assertEquals("foobar\nbaz", actual);
    }

    @Test
    void renderTagWithIdAndClass() {
        String actual = r.render(tag("test", attributes(id("bar"), className("foo")), text("foobar")));
        Assertions.assertEquals("<test id=\"bar\" class=\"foo\">\n" +
                "\tfoobar\n" +
                "</test>", actual);
    }

    @Test
    void renderText() {
        String actual = r.render(body(text("foobar")));
        Assertions.assertEquals("<body>\n" +
                "\tfoobar\n" +
                "</body>", actual);
    }

    @Test
    void renderBody() {
        String actual = r.render(body(text("foobar")));
        Assertions.assertEquals("<body>\n" +
                "\tfoobar\n" +
                "</body>", actual);
    }

    @Test
    void renderHead() {
        String actual = r.render(head());
        Assertions.assertEquals("<head></head>", actual);
    }

    @Test
    void renderTitle() {
        String actual = r.render(title(text("foo")));
        Assertions.assertEquals("<title>\n\tfoo\n</title>", actual);
    }

    @Test
    void renderMetaCharset() {
        String actual = r.render(meta(
                attributes(
                        charset(Charset.Name.UTF8)
                )
        ));
        Assertions.assertEquals("<meta charset=\"UTF-8\" />", actual);
    }
}
